runtime: python27
api_version: 1
threadsafe: true
skip_files:
- /*.json/
- /*.md/
- node_modules/
- config/
- public/

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
